export const FETCH_SUMMONER = 'FETCH_SUMMONER';
export const FETCH_SUMMONER_SUCCEESS = 'FETCH_SUMMONER_SUCCEESS';
export const FETCH_SUMMONER_ERROR = 'FETCH_SUMMONER_ERROR';
export const FETCH_TOP_SUMMONER = 'FETCH_TOP_SUMMONER';
export const FETCH_TOP_SUMMONER_SUCCEESS = 'FETCH_TOP_SUMMONER_SUCCEESS';
export const FETCH_TOP_SUMMONER_ERROR = 'FETCH_TOP_SUMMONER_ERROR';
export const FETCH_SUMMONER_DETAILS = 'FETCH_SUMMONER_DETAILS';
export const FETCH_SUMMONER_DETAILS_SUCCEESS = 'FETCH_SUMMONER_DETAILS_SUCCEESS';
export const FETCH_SUMMONER_DETAILS_ERROR = 'FETCH_SUMMONER_DETAILS_ERROR';
export const FETCH_MATCH = 'FETCH_MATCH';
export const FETCH_MATCH_SUCCESS = 'FETCH_MATCH_SUCCESS';
export const FETCH_MATCH_ERROR = 'FETCH_MATCH_ERROR';
export const FETCH_MATCH_DETAILS = 'FETCH_MATCH_DETAIL';
export const FETCH_MATCH_DETAILS_SUCCESS = 'FETCH_MATCH_DETAIL_SUCCESS';
export const FETCH_MATCH_DETAILS_ERROR = 'FETCH_MATCH_DETAIL_ERROR';

export const ADD_MATCH_DETAILS_ID = 'ADD_MATCH_DETAILS_ID';
export const CLEAN_UP_DETAILS = "CLEAN_UP_DETAILS";

export const REMOVE_MATCH_DETAILS = 'ADD_MATCH_DETAILS';

export const CLEAN_UP = 'CLEAN_UP';